#作者:自动畅
#微信号:auto-chang
#公众号：畅聊了个科技(IT-chang)
#Time：Saturday, April 22, 2023
#Describe：Power Generation for Love

FROM ubuntu-zlm-ffmpeg-dotnet AS keeper
WORKDIR /root/src
COPY . .
RUN mkdir -p /root/AKStreamKeeper 
WORKDIR /root/src/AKStreamKeeper
RUN ln -s $HOME/dotnet/dotnet /usr/bin/dotnet -f
RUN dotnet build "AKStreamKeeper.csproj" -c Release  -o /app/build
RUN dotnet publish  "AKStreamKeeper.csproj" -c Release  -o /app/publish
EXPOSE 80
EXPOSE 443
EXPOSE 6880
RUN mv  /app/publish/* /root/AKStreamKeeper
WORKDIR /root/AKStreamKeeper