# 使用我们的基础镜像
FROM zlmediakit-dotnet AS keeper

# 设置工作目录
WORKDIR /root/src

# 复制项目文件
COPY . .

# 创建必要的目录
RUN mkdir -p /root/AKStreamKeeper 

# 设置工作目录到项目目录
WORKDIR /root/src/AKStreamKeeper

# 构建项目
RUN dotnet build "AKStreamKeeper.csproj" -c Release -o /app/build
RUN dotnet publish "AKStreamKeeper.csproj" -c Release -o /app/publish

# 暴露必要的端口
EXPOSE 80
EXPOSE 443
EXPOSE 6880

# 移动编译后的文件到目标目录
RUN mv /app/publish/* /root/AKStreamKeeper

# 更新配置文件中的路径
RUN sed -i 's|"MediaServerPath": "[^"]*"|"MediaServerPath": "/opt/media/bin/MediaServer"|' /root/AKStreamKeeper/Config/AKStreamKeeper.json && \
    sed -i 's|"FFmpegPath": "[^"]*"|"FFmpegPath": "/usr/bin/ffmpeg"|' /root/AKStreamKeeper/Config/AKStreamKeeper.json

# 启动 MediaServer 并等待 5 秒后终止
RUN nohup /opt/media/bin/MediaServer & \
    sleep 5 && \
    pkill MediaServer || true

# 设置工作目录
WORKDIR /root/AKStreamKeeper